name: Deploy Frontend

on:
  push:
    branches: [main]
    paths: [frontend/**]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::105959917209:role/github-actions-cloud-resume-s3-deploy
          aws-region: us-east-1

      - run: aws s3 sync frontend/ s3://cloud-resume-zhnkevin-us-east-1/ --delete
